version: '3'
services:
  serve:
    build:
      context: .
      dockerfile: ./docs.Dockerfile
    image: squidfunk/mkdocs-material:9.5.44-custom
    container_name: s3fs-nio-docs
    working_dir: /workspace/docs
    volumes:
      - ../:/workspace
    ports:
      - 8000:8000
  build:
    build:
      context: .
      dockerfile: ./docs.Dockerfile
    image: squidfunk/mkdocs-material:9.5.44-custom
    working_dir: /workspace/docs
    command: [ "build" ]
    volumes:
      - ../:/workspace
